// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAyHQk4F1XzDctyOxYcOSEpcMqPQkVBRM',
    appId: '1:1066442986736:web:e5f5c14063214e31579e35',
    messagingSenderId: '1066442986736',
    projectId: 'gps-baby-care',
    authDomain: 'gps-baby-care.firebaseapp.com',
    storageBucket: 'gps-baby-care.appspot.com',
    measurementId: 'G-4LKS4NH1H0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2tFMfulVgpQSNUDJRRtj84WvKjXw_d2g',
    appId: '1:1066442986736:android:d3d56543d833bc3f579e35',
    messagingSenderId: '1066442986736',
    projectId: 'gps-baby-care',
    storageBucket: 'gps-baby-care.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAykIix8TwjbDb8oS9VJ6d3HVn4oy4kQzE',
    appId: '1:1066442986736:ios:7a9dd653d5ab8860579e35',
    messagingSenderId: '1066442986736',
    projectId: 'gps-baby-care',
    storageBucket: 'gps-baby-care.appspot.com',
    iosBundleId: 'com.babycare.gpsBabyCare',
  );
}
